"""add seller action logs

Revision ID: d44ae697eef7
Revises: 7ef13cb1e379
Create Date: 2026-09-25 10:45:43.108495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd44ae697eef7'
down_revision: Union[str, Sequence[str], None] = '7ef13cb1e379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_profile_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('approved', 'rejected', name='seller_action'), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['seller_profile_id'], ['seller_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seller_action_logs')
    # ### end Alembic commands ###
