"""add product moderation logs and seller action enum values

Revision ID: ec46fd773085
Revises: 836dbf0eef33
Create Date: 2026-09-25 15:35:16.776004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec46fd773085'
down_revision: Union[str, Sequence[str], None] = '836dbf0eef33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_moderation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('removed', 'suspended', 'reinstated', name='moderation_action'), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Not auto-detected: new SellerAction enum values for seller suspend/reinstate.
    op.execute("ALTER TYPE seller_action ADD VALUE IF NOT EXISTS 'suspended'")
    op.execute("ALTER TYPE seller_action ADD VALUE IF NOT EXISTS 'reinstated'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_moderation_logs')
    # ### end Alembic commands ###

    # Postgres has no direct "DROP VALUE" for enums; removing 'suspended'/'reinstated' from
    # seller_action would require rebuilding the type, not worth it for this project's scale
    # (see operations.md > Database Migrations: simple migrations, no zero-downtime discipline).
